esp_toml_version = 1.0

# Base URL of the file server where the images are available
firmware_images_url = "https://adwait-esp.github.io/flasher/images/"

supported_apps = ["Matter-All Clusters App"]

[Matter-All Clusters App]
chipsets = ["ESP32", "ESP32-C3"]
image.esp32 = "esp32_matter_all-clusters-app_te6_merged.bin"
image.esp32-c3 = "esp32c3_matter_all-clusters-app_te6_merged.bin"
ios_app_url = ""
android_app_url = ""